### ISSUE TITLE
bug: Current step is still highlighted when run is complete 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#9480]
# Overview

Protocol is complete but last step has remained highlighted as current step 
Behavior is present in json and python protocols 

# Current behavior
![Screen Shot 2022-02-15 at 3 27 59 PM](https://user-images.githubusercontent.com/30632549/154161087-8c919dad-de73-4535-abd7-883f67109b24.png)

**Comment by nusrat813** [comment]
Check if we can repo - python and json

**Comment by anthonywilleee** [comment]
@brenthagen was this fixed by your run log work?

**Comment by brenthagen** [comment]
@anthonywilleee this is still an issue, but we can address soon as we polish the new run log
